application: andrewjenny-1285
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts 

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /life/assets
  static_dir: life/assets

- url: /life/images
  static_dir: life/images

- url: /life/fonts
  static_dir: life/fonts 

- url: /life/favicon.ico
  static_files: life/static/favicon.ico
  upload: life/static/favicon.ico

- url: /timeline/assets
  static_dir: timeline/assets

- url: /timeline/images
  static_dir: timeline/images

- url: /timeline/fonts
  static_dir: timeline/fonts 

- url: /timeline/favicon.ico
  static_files: timeline/static/favicon.ico
  upload: timeline/static/favicon.ico

- url: /.*
  script: andrewjenny.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
