#application: andrewjenny-1285
runtime: python27
api_version: 1
threadsafe: true

handlers:
#AndrewJenny Resources
- url: /assets
  static_dir: assets

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts 

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

#Story Resources
- url: /pages/story/assets
  static_dir: pages/story/assets

- url: /pages/story/images
  static_dir: pages/story/images

- url: /pages/story/fonts
  static_dir: pages/story/fonts 

- url: /pages/story/favicon.ico
  static_files: pages/story/static/favicon.ico
  upload: pages/story/static/favicon.ico

#Life Resources
- url: /pages/life/assets
  static_dir: pages/life/assets

- url: /pages/life/images
  static_dir: pages/life/images

- url: /pages/life/fonts
  static_dir: pages/life/fonts 

- url: /pages/life/favicon.ico
  static_files: pages/life/static/favicon.ico
  upload: pages/life/static/favicon.ico

#Timeline Resources
- url: /pages/timeline/assets
  static_dir: pages/timeline/assets

- url: /pages/timeline/images
  static_dir: pages/timeline/images

- url: /pages/timeline/fonts
  static_dir: pages/timeline/fonts 

- url: /pages/timeline/favicon.ico
  static_files: pages/timeline/static/favicon.ico
  upload: pages/timeline/static/favicon.ico

#Xmas2019 Resources
- url: /pages/xmas2019/assets
  static_dir: pages/xmas2019/assets

- url: /pages/xmas2019/images
  static_dir: pages/xmas2019/images

- url: /pages/xmas2019/fonts
  static_dir: pages/xmas2019/fonts 

- url: /pages/xmas2019/favicon.ico
  static_files: pages/xmas2019/static/favicon.ico
  upload: pages/xmas2019/static/favicon.ico

#BDay2021 Resources
- url: /pages/bday/assets
  static_dir: pages/bday/assets

- url: /pages/bday/images
  static_dir: pages/bday/images

- url: /pages/bday/fonts
  static_dir: pages/bday/fonts 

- url: /pages/bday/favicon.ico
  static_files: pages/bday/static/favicon.ico
  upload: pages/bday/static/favicon.ico

#VDay2021 Resources
- url: /pages/vday/assets
  static_dir: pages/vday/assets

- url: /pages/vday/images
  static_dir: pages/vday/images

- url: /pages/vday/fonts
  static_dir: pages/vday/fonts 

- url: /pages/vday/favicon.ico
  static_files: pages/vday/static/favicon.ico
  upload: pages/vday/static/favicon.ico

#VDay2022 Resources
- url: /pages/vday22/assets
  static_dir: pages/vday22/assets

- url: /pages/vday22/images
  static_dir: pages/vday22/images

- url: /pages/vday22/fonts
  static_dir: pages/vday22/fonts 

- url: /pages/vday22/favicon.ico
  static_files: pages/vday22/static/favicon.ico
  upload: pages/vday22/static/favicon.ico

#Everything else
- url: /.*
  script: andrewjenny.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
